export const countries = [
  {
    name: 'United States',
    capital: 'Washington, D.C.',
    region: 'Americas',
    population: 331002651,
  },
  {
    name: 'Canada',
    capital: 'Ottawa',
    region: 'Americas',
    population: 37742154,
  },
  {
    name: 'Brazil',
    capital: 'Brasília',
    region: 'Americas',
    population: 212559417,
  },
  {
    name: 'Mexico',
    capital: 'Mexico City',
    region: 'Americas',
    population: 128932753,
  },
  {
    name: 'United Kingdom',
    capital: 'London',
    region: 'Europe',
    population: 67886011,
  },
  { name: 'France', capital: 'Paris', region: 'Europe', population: 65273511 },
  {
    name: 'Germany',
    capital: 'Berlin',
    region: 'Europe',
    population: 83783942,
  },
  {
    name: 'Russia',
    capital: 'Moscow',
    region: 'Europe/Asia',
    population: 145934462,
  },
  { name: 'China', capital: 'Beijing', region: 'Asia', population: 1439323776 },
  { name: 'Japan', capital: 'Tokyo', region: 'Asia', population: 126476461 },
  {
    name: 'India',
    capital: 'New Delhi',
    region: 'Asia',
    population: 1380004385,
  },
  {
    name: 'Australia',
    capital: 'Canberra',
    region: 'Oceania',
    population: 25499884,
  },
  {
    name: 'New Zealand',
    capital: 'Wellington',
    region: 'Oceania',
    population: 4822233,
  },
  {
    name: 'South Africa',
    capital: 'Pretoria',
    region: 'Africa',
    population: 59308690,
  },
  { name: 'Egypt', capital: 'Cairo', region: 'Africa', population: 102334404 },
  {
    name: 'Nigeria',
    capital: 'Abuja',
    region: 'Africa',
    population: 206139589,
  },
  { name: 'Kenya', capital: 'Nairobi', region: 'Africa', population: 53771296 },
  {
    name: 'South Korea',
    capital: 'Seoul',
    region: 'Asia',
    population: 51269185,
  },
  { name: 'Italy', capital: 'Rome', region: 'Europe', population: 60461826 },
  {
    name: 'Argentina',
    capital: 'Buenos Aires',
    region: 'Americas',
    population: 45195774,
  },
];
